# pages/3_draft_review.py

import streamlit as st
import datetime
import config
from pipeline.drafting import DraftingPipeline

# ── Guard ──────────────────────────────────────────────────────────────────────
if not st.session_state.get("current_prospect"):
    st.warning("No prospect in session. Start from ICP Setup.")
    if st.button("← Back to start"):
        st.switch_page("pages/1_icp_setup.py")
    st.stop()

prospect   = st.session_state.current_prospect
enrichment = st.session_state.get("current_enrichment")
score      = st.session_state.get("current_score")
profile    = st.session_state.get("active_profile")

if not enrichment or not score:
    st.warning("Enrichment or scoring not complete. Go back to Prospect page.")
    if st.button("← Back to prospect"):
        st.switch_page("pages/2_prospect_found.py")
    st.stop()

# ── Progress bar ───────────────────────────────────────────────────────────────
st.title(f"✏️ Draft review — {prospect.company_name}")
st.caption("Step 3 of 4 — review and approve the AI-generated outreach")

steps     = ["⚙️ ICP setup", "🔍 Prospect", "✏️ Draft review", "📊 Audit"]
step_cols = st.columns(len(steps))
for i, (col, label) in enumerate(zip(step_cols, steps), 1):
    color  = config.AGENCY_COLOR if i == 3 else (
        "#27AE60" if i < 3 else "#BDC3C7"
    )
    weight = "bold" if i == 3 else "normal"
    col.markdown(
        f"<div style='text-align:center;color:{color};"
        f"font-weight:{weight};font-size:13px;'>"
        f"{'●' if i==3 else ('✓' if i<3 else '○')} {label}</div>",
        unsafe_allow_html=True,
    )
st.divider()

# ── Generate drafts if not already done ───────────────────────────────────────
if not st.session_state.get("current_draft"):
    timestamps = st.session_state.get("current_timestamps", {})

    with st.spinner(
        "Generating research brief and outreach drafts "
        "(Mistral-7B-Instruct)..."
    ):
        timestamps["briefing_start"] = datetime.datetime.now().isoformat()
        drafter = DraftingPipeline()
        draft   = drafter.draft(prospect, enrichment, score, profile)
        timestamps["briefing_end"] = datetime.datetime.now().isoformat()
        timestamps["writing_start"] = timestamps["briefing_end"]
        timestamps["writing_end"]   = datetime.datetime.now().isoformat()

    st.session_state.current_draft      = draft
    st.session_state.current_timestamps = timestamps

    # confirm regeneration visibly — without HF_TOKEN the fallback templates
    # are deterministic, so the toast is the user's main signal that a fresh
    # call ran
    if st.session_state.pop("just_regenerated", False):
        st.toast("🔄 Drafts regenerated", icon="✅")
else:
    draft = st.session_state.current_draft

# ── Research brief ────────────────────────────────────────────────────────────
st.subheader("📋 Research brief")
st.caption(
    "5-bullet analyst summary — generated by Mistral-7B from enrichment data."
)

if draft.brief_bullets:
    for bullet in draft.brief_bullets:
        # render bold category labels
        if "**" in bullet:
            st.markdown(f"• {bullet}")
        else:
            st.markdown(f"• {bullet}")
else:
    st.info("Brief not available.")

# top signal callout
if score.top_signal_text:
    st.markdown(
        f"<div style='background:#EBF5FB;"
        f"border-left:4px solid {config.AGENCY_COLOR};"
        f"padding:10px 14px;border-radius:4px;margin:12px 0;'>"
        f"<div style='font-size:11px;color:#666;"
        f"text-transform:uppercase;'>Opening hook for email</div>"
        f"<div style='font-size:13px;font-weight:bold;"
        f"color:{config.AGENCY_COLOR};margin-top:4px;'>"
        f"{draft.opening_signal}</div>"
        f"</div>",
        unsafe_allow_html=True,
    )

# personalisation tags
if draft.personalisation_tags:
    st.markdown("**Signals used in this draft:**")
    chips = " ".join(
        f"<span style='background:#EBF5FB;"
        f"color:{config.AGENCY_COLOR};padding:3px 10px;"
        f"border-radius:10px;margin:2px;display:inline-block;"
        f"font-size:11px;'>{tag}</span>"
        for tag in draft.personalisation_tags
    )
    st.markdown(chips, unsafe_allow_html=True)

st.divider()

# ── Draft review tabs ──────────────────────────────────────────────────────────
st.subheader("✉️ Generated outreach")
st.caption(
    "Edit any field before approving. "
    "All edits are recorded and used to improve future drafts."
)

tab_email, tab_linkedin = st.tabs(["📧 Email", "💼 LinkedIn"])

with tab_email:
    # check if previously approved/edited
    existing_status = draft.approval_status
    if existing_status in ["approved", "edited_approved"]:
        st.success(
            f"✅ Already approved "
            f"({'with edits' if draft.was_edited else 'as generated'})"
        )

    email_subject = st.text_input(
        "Subject line",
        value       = draft.edited_subject or draft.email_subject,
        key         = "email_subject_input",
    )
    email_body = st.text_area(
        "Email body",
        value       = draft.edited_body or draft.email_body,
        height      = 280,
        key         = "email_body_input",
    )

    word_count = len(email_body.split()) if email_body else 0
    color      = (
        "#27AE60" if word_count <= 100 else
        "#F39C12" if word_count <= 130 else
        "#E74C3C"
    )
    st.markdown(
        f"<div style='font-size:12px;color:{color};'>"
        f"Word count: {word_count} / 100 recommended</div>",
        unsafe_allow_html=True,
    )

with tab_linkedin:
    linkedin_msg = st.text_area(
        "LinkedIn message",
        value       = draft.edited_linkedin or draft.linkedin_message,
        height      = 120,
        key         = "linkedin_input",
        help        = "Keep under 300 characters for connection requests.",
    )
    char_count = len(linkedin_msg) if linkedin_msg else 0
    color      = "#27AE60" if char_count <= 300 else "#E74C3C"
    st.markdown(
        f"<div style='font-size:12px;color:{color};'>"
        f"Characters: {char_count} / 300</div>",
        unsafe_allow_html=True,
    )

    # phone mockup for LinkedIn message
    if linkedin_msg:
        st.markdown("**Preview:**")
        st.markdown(
            f"<div style='background:#2C3E50;color:white;"
            f"border-radius:16px;padding:14px 18px;"
            f"max-width:320px;font-size:13px;line-height:1.5;'>"
            f"{linkedin_msg}</div>",
            unsafe_allow_html=True,
        )
        st.caption(
            "Copy this text and paste into LinkedIn. "
            "Do not automate LinkedIn sending — account safety risk."
        )

st.divider()

# ── Regenerate ─────────────────────────────────────────────────────────────────
# show when the current draft was generated so regeneration is visibly
# distinct even if the fallback templates produce the same text
if getattr(draft, "drafted_at", ""):
    try:
        ts = datetime.datetime.fromisoformat(draft.drafted_at)
        st.caption(f"Drafted at {ts.strftime('%H:%M:%S')}")
    except (ValueError, TypeError):
        pass

if st.button("🔄 Regenerate drafts", use_container_width=False):
    # clear cached draft AND the widget-bound keys so text_input/text_area
    # pick up the new draft's `value=` instead of the stale session state
    st.session_state.current_draft = None
    for k in ("email_subject_input", "email_body_input", "linkedin_input"):
        st.session_state.pop(k, None)
    st.session_state["just_regenerated"] = True
    st.rerun()

st.divider()

# ── Approve / Reject ───────────────────────────────────────────────────────────
st.subheader("Your decision")
st.caption(
    "Approve to proceed to the audit summary and Salesforce export. "
    "Reject to return to prospect selection. "
    "Both decisions are recorded."
)

col_approve, col_reject = st.columns(2)

with col_approve:
    reason_placeholder = st.empty()
    if st.button(
        "✅ Approve and continue",
        type             = "primary",
        use_container_width = True,
    ):
        current_email_subject = st.session_state.get(
            "email_subject_input", draft.email_subject)
        current_email_body    = st.session_state.get(
            "email_body_input", draft.email_body)
        current_linkedin      = st.session_state.get(
            "linkedin_input", draft.linkedin_message)

        draft.approve(
            edited_body     = current_email_body,
            edited_subject  = current_email_subject,
            edited_linkedin = current_linkedin,
        )
        st.session_state.current_draft = draft

        # record decision in ICP profile
        if profile:
            profile.record_approval(
                prospect_id = prospect.domain,
                signals     = (
                    enrichment.triggers_fired
                    if enrichment and hasattr(enrichment, "triggers_fired")
                    else []
                ),
            )
            if draft.was_edited:
                profile.record_edit(
                    prospect_id = prospect.domain,
                    original    = draft.email_body,
                    edited      = current_email_body,
                )

        # save completed result to all_results
        all_results = st.session_state.get("all_results", [])
        # remove previous entry for this prospect if exists
        all_results = [
            r for r in all_results
            if r.get("prospect", {}).get("domain") != prospect.domain
        ]
        all_results.append({
            "prospect":   prospect.to_dict(),
            "enrichment": enrichment.to_dict(),
            "score":      score.to_dict(),
            "draft":      draft.to_dict(),
        })
        st.session_state.all_results = all_results

        st.success(
            f"✅ Approved "
            f"{'(with edits)' if draft.was_edited else '(as generated)'}. "
            f"Moving to audit summary."
        )
        st.switch_page("pages/4_audit_summary.py")

with col_reject:
    rejection_reason = st.text_input(
        "Rejection reason (optional — helps improve scoring)",
        placeholder = "e.g. too small, already signed a lease...",
        key         = "rejection_reason",
    )
    if st.button(
        "❌ Reject — not a fit",
        use_container_width = True,
    ):
        draft.reject(reason=rejection_reason)
        st.session_state.current_draft = draft

        if profile:
            profile.record_rejection(
                prospect_id = prospect.domain,
                reason      = rejection_reason,
            )

        st.warning(
            "Prospect rejected. "
            "Returning to prospect selection."
        )
        st.session_state.current_prospect   = None
        st.session_state.current_enrichment = None
        st.session_state.current_score      = None
        st.session_state.current_draft      = None
        st.switch_page("pages/1_icp_setup.py")